[package]
name = "jid"
version = "0.1.0"
edition = "2024"
description = "A distraction-free writing app"
license = "MIT"

[dependencies]
gpui = { version = "*" }
dirs = "5"
unicode-segmentation = "1"
chrono = "0.4"
serde = { version = "1", features = ["derive"] }
toml = "0.8"
